### ISSUE TITLE
方便封装成dll吗

### ISSUE THREAD

**Issue by GengGode** [aixcyi/genshin-gacha-kit#1]
可不可能整出来dll然后c++调用

**Comment by aixcyi** [comment]
Python确实可以打包成DLL，但是体积比较大，所以暂时没在考虑范围。
要是有兴趣的话可以用C#、C++或者其他语言重写。
（主要是懒，雾

**Comment by aixcyi** [comment]
而且捏，下一步我计划开一个新仓库，用JavaScript重写，然后用electron写一个图形界面
（但后端的俺还是咕咕咕算了，逃

**Comment by GengGode** [comment]
啊这，太可惜了。
那就等你的图形面，正好可以作为模组和启动器联动
![Q1%334LJ93G}S4CWZ5WB1%H](https://user-images.githubusercontent.com/47711102/127436658-5dda4717-563e-404f-87bb-47bb47bc0deb.gif)

**Comment by aixcyi** [comment]
咕咕：说的是本咕吗？

**Comment by GengGode** [comment]
咕咕2：不急，我的新版本也在咕，o(￣▽￣)ｄ
